/*
 * Copyright (C) 2026, Wen-Xuan Zhang <serialcore@outlook.com>
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * SONN Network implementation — high-level semantics.
 *
 * This layer builds meaningful neural network behavior on top of the raw Pool:
 *   - Tracks which neurons are "active" from the user's perspective.
 *   - Manages activation types.
 *   - Handles edge creation with proper semantic rules.
 *   - Provides convenient query APIs.
 *
 * All raw memory allocation and slot management is delegated to the Pool.
 */

#include <serialcore/sonn/network.h>

#include <stdlib.h>
#include <string.h>

network_t* network_create(int max_neurons, int input_dim) {
    if (max_neurons <= 0) return NULL;
    if (input_dim <= 0) return NULL;

    network_t *net = (network_t*)calloc(1, sizeof(network_t));
    if (!net) return NULL;

    net->pool = nnpool_create(max_neurons, input_dim);
    if (!net->pool) {
        free(net);
        return NULL;
    }

    net->current_neurons = 0;
    return net;
}

void network_destroy(network_t *net) {
    if (!net) return;
    if (net->pool) {
        nnpool_destroy(net->pool);
    }
    free(net);
}

int network_add_neuron(network_t *net, activaton_t type) {
    if (!net || !net->pool) return -1;

    /* All neuron semantic operations are performed in the Network layer.
     * Network is only responsible for acquiring storage slots and organizing the network.
     * Neuron IDs are pre-generated by the Pool at creation time for all slots.
     * Network has no authority to assign or modify IDs.
     */
    int slot = nnpool_acquire_slot(net->pool);
    if (slot < 0) return -1;

    neuron_t *n = nnpool_get_neuron(net->pool, slot);
    float *params = nnpool_get_params(net->pool, slot);

    int *row = nnpool_adjacency_row(net->pool, slot);
    if (row) {
        for (int s = 0; s < net->pool->max_degree; s++) {
            row[s] = -1;
        }
    }
    net->pool->degrees[slot] = 0;

    /* Activate the neuron (ID was already assigned at Pool creation time) */
    if (n) {
        neuron_activate(n, type, params, net->pool->input_dim);
    }

    net->current_neurons++;
    return slot;
}

void network_remove_neuron(network_t *net, int id) {
    if (!net || !net->pool) return;
    if (id < 0 || id >= net->pool->max_neurons) return;

    neuron_t *n = nnpool_get_neuron(net->pool, id);
    if (!n || !n->active) return;

    neuron_deactivate(n);

    /* Remove all incident edges (semantic cleanup) */
    int md = net->pool->max_degree;
    int *row = nnpool_adjacency_row(net->pool, id);
    if (row) {
        for (int s = 0; s < md; s++) {
            int to = row[s];
            if (to >= 0) {
                network_remove_edge(net, id, to);
            }
        }
    }

    /* Remove reverse edges from other neurons */
    for (int i = 0; i < net->pool->max_neurons; i++) {
        neuron_t *other = nnpool_get_neuron(net->pool, i);
        if (!other || !other->active) continue;
        int *orow = nnpool_adjacency_row(net->pool, i);
        if (!orow) continue;
        for (int s = 0; s < md; s++) {
            if (orow[s] == id) {
                orow[s] = -1;
                net->pool->degrees[i]--;
            }
        }
    }

    /* Release the raw slot back to the pool (pure memory operation) */
    nnpool_release_slot(net->pool);
    net->current_neurons--;
}

int network_add_edge(network_t *net, int from, int to, float strength) {
    if (!net || !net->pool) return -1;
    if (from < 0 || to < 0 || from >= net->pool->max_neurons || to >= net->pool->max_neurons) return -1;
    if (from == to) return -1;

    neuron_t *nf = nnpool_get_neuron(net->pool, from);
    neuron_t *nt = nnpool_get_neuron(net->pool, to);
    if (!nf || !nt || !nf->active || !nt->active) return -1;

    int md = net->pool->max_degree;
    int slot = nnpool_find_edge_slot(net->pool, from, to);

    if (slot >= 0) {
        /* Update existing */
        int eidx = from * md + slot;
        net->pool->edges[eidx].strength = strength;
        net->pool->edges[eidx].age = 0;
        return eidx;
    }

    if (net->pool->degrees[from] >= md) return -1;

    /* Find free slot in adjacency row */
    int *row = nnpool_adjacency_row(net->pool, from);
    slot = -1;
    for (int s = 0; s < md; s++) {
        if (row[s] == -1) {
            slot = s;
            break;
        }
    }
    if (slot < 0) return -1;

    int eidx = from * md + slot;
    row[slot] = to;
    net->pool->degrees[from]++;

    edge_t *e = &net->pool->edges[eidx];
    e->from = from;
    e->to = to;
    e->strength = strength;
    e->age = 0;
    e->active = 1;

    /* Optional reverse edge (GNG style) */
    int rslot = nnpool_find_edge_slot(net->pool, to, from);
    if (rslot < 0 && net->pool->degrees[to] < md) {
        int *rrow = nnpool_adjacency_row(net->pool, to);
        for (int s = 0; s < md; s++) {
            if (rrow[s] == -1) {
                rrow[s] = from;
                net->pool->degrees[to]++;
                int re = to * md + s;
                edge_t *re_e = &net->pool->edges[re];
                re_e->from = to;
                re_e->to = from;
                re_e->strength = strength;
                re_e->age = 0;
                re_e->active = 1;
                break;
            }
        }
    }

    return eidx;
}

void network_remove_edge(network_t *net, int from, int to) {
    if (!net || !net->pool) return;

    int md = net->pool->max_degree;
    int slot = nnpool_find_edge_slot(net->pool, from, to);
    if (slot >= 0) {
        int *row = nnpool_adjacency_row(net->pool, from);
        row[slot] = -1;
        net->pool->degrees[from]--;
        net->pool->edges[from * md + slot].active = 0;
    }

    int rslot = nnpool_find_edge_slot(net->pool, to, from);
    if (rslot >= 0) {
        int *rrow = nnpool_adjacency_row(net->pool, to);
        rrow[rslot] = -1;
        net->pool->degrees[to]--;
        net->pool->edges[to * md + rslot].active = 0;
    }
}

int network_get_neighbors(network_t *net, int id, int *out, int max_out) {
    if (!net || !net->pool || id < 0 || !out || max_out <= 0) return 0;
    neuron_t *n = nnpool_get_neuron(net->pool, id);
    if (!n || !n->active) return 0;

    int md = net->pool->max_degree;
    int *row = nnpool_adjacency_row(net->pool, id);
    if (!row) return 0;

    int count = 0;
    for (int s = 0; s < md && count < max_out; s++) {
        if (row[s] >= 0) out[count++] = row[s];
    }
    return count;
}

uint64_t network_get_neuronid(network_t *net, int slot)
{
    if (!net || !net->pool) return 0;
    neuron_t *n = nnpool_get_neuron(net->pool, slot);
    return n ? n->id : 0;
}

nnpool_t* network_get_pool(network_t *net) {
    return net ? net->pool : NULL;
}
