/*
 * Copyright (C) 2026, Wen-Xuan Zhang <serialcore@outlook.com>
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * SONN Network implementation — high-level semantics.
 *
 * This layer builds meaningful neural network behavior on top of the raw Pool:
 *   - Tracks which neurons are "active" from the user's perspective.
 *   - Manages activation types.
 *   - Handles edge creation with proper semantic rules.
 *   - Provides convenient query APIs.
 *
 * All raw memory allocation and slot management is delegated to the Pool.
 */

#include <serialcore/sonn/network.h>

#include <stdlib.h>
#include <string.h>

network_t* network_create(int max_neurons, int input_dim, int max_degree, int seed)
{
    if (max_neurons <= 0) return NULL;
    if (input_dim <= 0) return NULL;
    if (max_degree <= 0) max_degree = SONN_DEFAULT_MAX_DEGREE;  /* from nnpool.h */

    network_t *net = (network_t*)calloc(1, sizeof(network_t));
    if (!net) return NULL;

    net->pool = nnpool_create(max_neurons, input_dim, max_degree, seed);
    if (!net->pool) {
        free(net);
        return NULL;
    }

    net->current_neurons = 0;
    net->max_neurons = max_neurons;
    net->max_degree = max_degree;
    net->input_dim = input_dim;
    net->seed = seed;
    return net;
}

void network_destroy(network_t *net)
{
    if (!net) return;

    if (net->pool) {
        nnpool_destroy(net->pool);
    }
    free(net);
}

int network_add_neuron(network_t *net, activaton_t type)
{
    if (!net || !net->pool) return -1;

    /* All neuron semantic operations are performed in the Network layer.
     * Network is only responsible for acquiring storage slots and organizing the network.
     * Neuron IDs are pre-generated by the Pool at creation time for all slots.
     * Network has no authority to assign or modify IDs.
     */
    int slot = nnpool_acquire_slot(net->pool);
    if (slot < 0) return -1;

    neuron_t *n = nnpool_get_neuron(net->pool, slot);
    float *params = nnpool_get_params(net->pool, slot);

    edge_t *erow = nnpool_edge_row(net->pool, slot);
    if (erow) {
        for (int s = 0; s < net->pool->max_degree; s++) {
            erow[s].active = 0;
            erow[s].to = -1;
        }
    }
    net->pool->degrees[slot] = 0;

    /* Activate the neuron (ID was already assigned at Pool creation time) */
    if (n) {
        neuron_activate(n, type, params, net->pool->input_dim);
    }

    net->current_neurons++;
    return slot;
}

void network_remove_neuron(network_t *net, int id)
{
    if (!net || !net->pool) return;
    if (id < 0 || id >= net->pool->max_neurons) return;

    neuron_t *n = nnpool_get_neuron(net->pool, id);
    if (!n || !n->active) return;

    neuron_deactivate(n);

    /* Remove all incident edges (semantic cleanup) */
    int md = net->pool->max_degree;
    edge_t *erow = nnpool_edge_row(net->pool, id);
    if (erow) {
        for (int s = 0; s < md; s++) {
            if (erow[s].active) {
                int to = erow[s].to;
                network_remove_edge(net, id, to);
            }
        }
    }

    /* Remove reverse edges from other neurons */
    for (int i = 0; i < net->pool->max_neurons; i++) {
        neuron_t *other = nnpool_get_neuron(net->pool, i);
        if (!other || !other->active) continue;
        edge_t *orow = nnpool_edge_row(net->pool, i);
        if (!orow) continue;
        for (int s = 0; s < md; s++) {
            if (orow[s].active && orow[s].to == id) {
                orow[s].active = 0;
                orow[s].to = -1;
                net->pool->degrees[i]--;
            }
        }
    }

    /* Release the raw slot back to the pool (pure memory operation) */
    nnpool_release_slot(net->pool, id);
    net->current_neurons--;
}

int network_add_edge(network_t *net, int from, int to, float weight)
{
    if (!net || !net->pool) return -1;
    if (from < 0 || to < 0 || from >= net->pool->max_neurons || to >= net->pool->max_neurons) return -1;
    if (from == to) return -1;

    neuron_t *nf = nnpool_get_neuron(net->pool, from);
    neuron_t *nt = nnpool_get_neuron(net->pool, to);
    if (!nf || !nt || !nf->active || !nt->active) return -1;

    int md = net->pool->max_degree;
    int slot = nnpool_find_edge_slot(net->pool, from, to);

    if (slot >= 0) {
        /* Update existing - update edge metadata and the weight in receiver's weights (Option A) */
        int eidx = from * md + slot;
        net->pool->edges[eidx].weight = 0.0f;   /* main weight no longer stored here (Option A) */
        net->pool->edges[eidx].age = 0;

        /* Update weight in the 'to' (receiver) neuron's weights vector if reverse slot exists */
        int rslot = nnpool_find_edge_slot(net->pool, to, from);
        if (rslot >= 0) {
            float *to_w = nnpool_get_params(net->pool, to);
            if (to_w) to_w[rslot + 1] = weight;
        }
        return eidx;
    }

    if (net->pool->degrees[from] >= md) return -1;

    /* Find free slot in this neuron's edge row */
    edge_t *row = nnpool_edge_row(net->pool, from);
    slot = -1;
    for (int s = 0; s < md; s++) {
        if (!row[s].active) {
            slot = s;
            break;
        }
    }
    if (slot < 0) return -1;

    int eidx = from * md + slot;
    net->pool->degrees[from]++;

    edge_t *e = &net->pool->edges[eidx];
    e->from = from;
    e->to = to;
    e->weight = 0.0f;   /* main weights now live in neuron->weights (Option A) */
    e->age = 0;
    e->active = 1;

    /* Reverse edge (always added when possible).
     * This is a deliberate design choice for SONN:
     * - Allows a neuron to easily iterate its *incoming* connections by walking its own edge row.
     * - The local slot index 's' in the receiver's row is used for indexing into receiver->weights[s] (Option A).
     * - For pure topology (future GNG), edges primarily provide connectivity + age.
     * This makes both layered forward passes and dynamic graph algorithms natural.
     */
    int rslot = nnpool_find_edge_slot(net->pool, to, from);
    if (rslot < 0 && net->pool->degrees[to] < md) {
        edge_t *rrow = nnpool_edge_row(net->pool, to);
        for (int s = 0; s < md; s++) {
            if (!rrow[s].active) {
                net->pool->degrees[to]++;
                int re = to * md + s;
                edge_t *re_e = &net->pool->edges[re];
                re_e->from = to;
                re_e->to = from;
                re_e->weight = 0.0f;
                re_e->age = 0;
                re_e->active = 1;

                /* Place the connection weight into the receiver's weights at this local slot index */
                float *to_w = nnpool_get_params(net->pool, to);
                if (to_w) {
                    to_w[s + 1] = weight;
                }
                break;
            }
        }
    } else if (rslot >= 0) {
        /* Existing reverse - update weight at receiver's slot */
        float *to_w = nnpool_get_params(net->pool, to);
        if (to_w) to_w[rslot + 1] = weight;
    }

    return eidx;
}

void network_remove_edge(network_t *net, int from, int to)
{
    if (!net || !net->pool) return;

    int md = net->pool->max_degree;
    int slot = nnpool_find_edge_slot(net->pool, from, to);
    if (slot >= 0) {
        edge_t *row = nnpool_edge_row(net->pool, from);
        row[slot].active = 0;
        row[slot].to = -1;
        net->pool->degrees[from]--;
        net->pool->edges[from * md + slot].active = 0;
    }

    int rslot = nnpool_find_edge_slot(net->pool, to, from);
    if (rslot >= 0) {
        edge_t *rrow = nnpool_edge_row(net->pool, to);
        rrow[rslot].active = 0;
        rrow[rslot].to = -1;
        net->pool->degrees[to]--;
        net->pool->edges[to * md + rslot].active = 0;

        /* Clear the corresponding weight slot on the receiver (Option A) */
        float *to_w = nnpool_get_params(net->pool, to);
        if (to_w) to_w[rslot + 1] = 0.0f;
    }
}

int network_get_neighbors(network_t *net, int id, int *out, int max_out)
{
    if (!net || !net->pool || id < 0 || !out || max_out <= 0) return 0;
    neuron_t *n = nnpool_get_neuron(net->pool, id);
    if (!n || !n->active) return 0;

    int md = net->pool->max_degree;
    edge_t *erow = nnpool_edge_row(net->pool, id);
    if (!erow) return 0;

    int count = 0;
    for (int s = 0; s < md && count < max_out; s++) {
        if (erow[s].active) out[count++] = erow[s].to;
    }
    return count;
}

uint64_t network_get_neuronid(network_t *net, int slot)
{
    if (!net || !net->pool) return 0;
    neuron_t *n = nnpool_get_neuron(net->pool, slot);
    return n ? n->id : 0;
}

nnpool_t* network_get_pool(network_t *net)
{
    return net ? net->pool : NULL;
}
