/*
 * Copyright (C) 2026, Wen-Xuan Zhang <serialcore@outlook.com>
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef SERIALCORE_SONN_NETWORK
#define SERIALCORE_SONN_NETWORK

#include <serialcore/sonn/activaton.h>
#include <serialcore/sonn/nnpool.h>

#include <stdint.h>

/*
 * SONN Network — neural network layer.
 *
 * Requirements:
 *   - All neural network configuration and operations are placed here.
 *   - Network is responsible for the "neuron" concept (add, remove, activation functions, etc.).
 *   - Network is responsible for edge semantics (add, remove, topology, age, etc.).
 *   - Main connection weights live in the target neuron's weights[] (indexed by local edge slot).
 *   - Network internally uses Pool to manage memory.
 *   - Pool is only responsible for basic memory management, access, and queries. It contains no neuron operations.
 */

typedef struct network {
    nnpool_t    *pool;             /* underlying memory pool (capacity and storage only) */

    /* Network configuration and state */
    int         current_neurons;      /* number of neurons currently in use */
    int         max_neurons;
    int         max_degree;
    int         input_dim;
    int         seed;
} network_t;

/* Lifecycle */
network_t* network_create(int max_neurons, int input_dim, int seed);
void network_destroy(network_t *net);

/* Neuron operations */
int  network_add_neuron(network_t *net, activaton_t type);
void network_remove_neuron(network_t *net, int id);

/* Edge operations */
int  network_add_edge(network_t *net, int from, int to, float weight);
void network_remove_edge(network_t *net, int from, int to);

/* Queries */
int network_get_neighbors(network_t *net, int id, int *out, int max_out);

/* Get the pre-assigned identity ID of the neuron at the given storage slot.
 * The ID was generated by the Pool at creation time.
 */
uint64_t network_get_neuronid(network_t *net, int slot);

/* Advanced: direct access to the underlying Pool (memory access only) */
nnpool_t* network_get_pool(network_t *net);

#endif
